name: Android XP2P RELEASE CI

on:
  release:
    types: [published]

env:
  IOT_SONATYPE_USERNAME: ${{ secrets.IOT_SONATYPE_USERNAME }}
  IOT_SONATYPE_PASSWORD: ${{ secrets.IOT_SONATYPE_PASSWORD }}
  GPG_DECRYPT_PASSPHRASE: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}
  IOT_GPG_KEYNAME: ${{ secrets.IOT_GPG_KEYNAME }}
  IOT_GPG_PASSPHRASE: ${{ secrets.IOT_GPG_PASSPHRASE }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: build libenet
      run: |
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        export GIT_BRANCH_IMAGE_VERSION=$VERSION
        
        sh .github/script/build_enet_android.sh
      env:
        GIT_ACCESS_TOKEN: ${{ secrets.IOT_GITHUB_ACCESS_TOKEN }}
        PROVISIONING_PASSWORD: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.8
      with:
        cmake-version: '3.18.4'
    - name: Use cmake
      run: echo +++++$(cmake --version)
    - name: Update Values of Signing
      run: |
        export KEY_ID_OF_SIGN=$IOT_GPG_KEYNAME
        export PASSWORD_OF_SIGN=$IOT_GPG_PASSPHRASE
        sh .github/script/update_values_for_sign.sh
    - name: Build with Gradle
      run: |
        gpg -d --passphrase "$GPG_DECRYPT_PASSPHRASE" --batch --quiet .github/file/secring.gpg.asc > secring.gpg
        echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;22.0.7026061"
        cmake_version=$(echo $(cmake --version) | perl -pe '($_)=/([0-9]+([.][0-9]+)+)/')
        echo +++++$cmake_version
        sed -i "s#x.x.x#$cmake_version#g" iot-p2p/samples/android/xnet/build.gradle
        sh .github/script/update_version_for_android.sh
        cd iot-p2p/samples/android
        ./gradlew assemble --stacktrace
    - name: Upload aar to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: xp2p.aar
        path: iot-p2p/samples/android/xnet/build/outputs/aar/*-release.aar

    - name: Publish aar to Maven
      run: |
        cd iot-p2p/samples/android
        ./gradlew publish
