name: Windows XP2P CI

on:
  push:
    paths-ignore: # 有時候不想要改個文档也触发 github actions
      - '**.md'
      - 'LICENSE'

jobs:
  build-and-deploy:
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.8
      with:
        cmake-version: '3.17.0'
    - name: Use cmake
      run: echo +++++$(cmake --version)
      
    - name: debug build libenet
      if: startsWith(github.event.ref, 'refs/heads')
      run: |
        $branch="${{ github.ref }}"
        $branch=$branch.Split("/")[2]
        echo $branch
        .\.github\script\build_enet_windows.cmd Debug $branch
      shell: pwsh
      env:
        GIT_ACCESS_TOKEN: ${{ secrets.IOT_GITHUB_ACCESS_TOKEN }}
        PROVISIONING_PASSWORD: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}

    - name: release build libenet
      if: startsWith(github.event.ref, 'refs/tags')
      run: |
        $branch="${{ github.ref }}"
        $branch=$branch.Split("/")[2]
        echo $branch
        sh .github/script/build_enet_windows.cmd Release $branch
      shell: pwsh
      env:
        GIT_ACCESS_TOKEN: ${{ secrets.IOT_GITHUB_ACCESS_TOKEN }}
        PROVISIONING_PASSWORD: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}
        
        
    - name: Compress SDK Artifacts
      run: |
        zip -r xp2p_windows.zip iot-p2p/samples/windows_p2p/p2p_sample
        
    - name: Upload Windows SDK Library
      uses: actions/upload-artifact@v2
      with:
        name: xp2p_windows_lib.zip
        path: xp2p_windows.zip
