name: iOS XP2P CI

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: build libenet
      if: startsWith(github.event.ref, 'refs/heads')
      run: |
        sh .github/script/build_enet_ios.sh Debug
      env:
        GIT_ACCESS_TOKEN: ${{ secrets.IOT_GITHUB_ACCESS_TOKEN }}
        PROVISIONING_PASSWORD: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}    

    - name: push libenet
      if: startsWith(github.event.ref, 'refs/heads')
      run: |
        sh .github/script/build_enet_ios.sh Release
      env:
        GIT_ACCESS_TOKEN: ${{ secrets.IOT_GITHUB_ACCESS_TOKEN }}
        PROVISIONING_PASSWORD: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}
        
    - name: Upload NETSDK Library
      uses: actions/upload-artifact@v2
      with:
        name: libenet_ios.a
        path: iot-p2p/build/ios/Release-iphoneos/libenet.a
