name: iOS XP2P CI

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
#    - if: "github.event.release.prerelease"
#      name: prebuild libenet
#      run: sh .github/script/build_enet_ios.sh Debug
#      env:
#        GIT_ACCESS_TOKEN: ${{ secrets.IOT_GITHUB_ACCESS_TOKEN }}
#        PROVISIONING_PASSWORD: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}

    - name: build libenet
      run: |
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        export GIT_BRANCH_IMAGE_VERSION=$VERSION
        
        sh .github/script/build_enet_ios.sh Release
        
      env:
        GIT_ACCESS_TOKEN: ${{ secrets.IOT_GITHUB_ACCESS_TOKEN }}
        PROVISIONING_PASSWORD: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}
        

    - name: Upload NETSDK Library
      uses: actions/upload-artifact@v2
      with:
        name: libenet_ios.a
        path: iot-p2p/components_src/eNet/build/ios/Release-iphoneos/libenet.a
